name: Custom Workflow
on:
  push:
    branches: [develop]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "18"
      - name: Install & Test
       run: |
          cd sample-app
          npm install
          npm test --force-Exit
